### ISSUE TITLE
Changing default sound device requires deletion of openloco.yml on next attempt to launch game.

### ISSUE THREAD

**Issue by Zcooger** [OpenLoco/OpenLoco#527]
OS: Windows 7 x64
Version: 25.05.1
Build: (d0d7686 on master)

Issue: I opened the game and change its sound device and then quit. When I attempted to start the game again, It never started, and only would do so after I deleted the openloco.yml file or edited its "audio: device: " parameter.

To reproduce:

1 Start the game.
2. Change sound device to other than default.
3. Close the game (playing anything isn't required).
4. Attempt to launch the game. It will fail and not give a reason why.

openloco.yml files which do not crash the game:
```
display:
  mode: fullscreen
  window_resolution:
    width: 800
    height: 600
  fullscreen_resolution:
    width: 1920
    height: 1200
audio:
  play_title_music: true
loco_install_path: F:\Program Files (x86)\Steam\steamapps\common\Locomotion
language: en-GB
breakdowns_disabled: false
scale_factor: 1
zoom_to_cursor: true
```
and
```display:
  mode: fullscreen
  window_resolution:
    width: 800
    height: 600
  fullscreen_resolution:
    width: 1920
    height: 1200
audio:
  play_title_music: true
  device:
loco_install_path: F:\Program Files (x86)\Steam\steamapps\common\Locomotion
language: en-GB
breakdowns_disabled: false
scale_factor: 1
zoom_to_cursor: true
```

openloco.yml file which does crash the game:
```display:
  mode: fullscreen
  window_resolution:
    width: 800
    height: 600
  fullscreen_resolution:
    width: 1920
    height: 1200
audio:
  play_title_music: true
  device: LINE OUT (ASUS Xonar DGX Audio Device)
loco_install_path: F:\Program Files (x86)\Steam\steamapps\common\Locomotion
language: en-GB
breakdowns_disabled: false
scale_factor: 1
zoom_to_cursor: true
```

Bug in original game: No. OpenLoco relies on files that the original game does not rely on.

Crash dunp file: https://drive.google.com/file/d/1ghO_ReOM-4X8uvNfduBm-hvMFQVv5ghd
